name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zap-scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Run application container
        run: docker run -d -p 5000:5000 --name cicd-demo-app cicd-demo:test
          
      - name: Wait for application
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:5000 2>/dev/null; then
              echo "Application ready"
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Test application connectivity
        run: |
          echo "=== Testing Application Connectivity ==="
          echo "From GitHub runner:"
          curl -I http://localhost:5000 || echo "Runner cannot reach localhost:5000"
          
          echo "From Docker container with host network:"
          docker run --network host curlimages/curl:latest curl -I http://localhost:5000 || echo "Container cannot reach localhost:5000"
          
          echo "Checking what's listening on port 5000:"
          netstat -tlnp | grep :5000 || echo "Nothing listening on port 5000"
          
          echo "Docker containers:"
          docker ps

      - name: Run ZAP Scan
        run: |
          echo "=== Starting ZAP Scan ==="
          docker run --network host \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            -u root \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:5000 \
            -r report.html \
            -J report.json \
            -w report.md \
            -d
        continue-on-error: true

      - name: Check generated files
        run: |
          echo "=== Checking for ZAP report files ==="
          ls -la ${{ github.workspace }}/
          find ${{ github.workspace }} -name "report*" -type f || echo "No report files found"

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-reports
          path: |
            report.html
            report.json
            report.md
          if-no-files-found: warn

      - name: Stop application
        if: always()
        run: docker stop cicd-demo-app && docker rm cicd-demo-app
