name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap-scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Run application container
        run: |
          docker run -d -p 5000:5000 --name cicd-demo-app cicd-demo:test
          
      - name: Wait for application to start
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:5000 2>/dev/null; then
              echo "Application is ready"
              exit 0
            fi
            echo "Waiting for application... ($i/30)"
            sleep 2
          done
          echo "Application failed to start"
          docker logs cicd-demo-app
          exit 1

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
            report_md.md

      - name: Stop application container
        if: always()
        run: docker stop cicd-demo-app && docker rm cicd-demo-app
